version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: crimsoncalendar-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crimson_calendar
    ports:
      - "5542:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: