"""create tables

Revision ID: 3e0de9eabde0
Revises: 
Create Date: 2025-05-01 00:43:20.664616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3e0de9eabde0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cyclephaseinfos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tips', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lh', sa.Float(), nullable=True),
    sa.Column('fsh', sa.Float(), nullable=True),
    sa.Column('estrogen', sa.Float(), nullable=True),
    sa.Column('progesterone', sa.Float(), nullable=True),
    sa.Column('androgen', sa.Float(), nullable=True),
    sa.Column('insulin', sa.Float(), nullable=True),
    sa.Column('prolactin', sa.Float(), nullable=True),
    sa.Column('testosterone', sa.Float(), nullable=True),
    sa.Column('cortisol', sa.Float(), nullable=True),
    sa.Column('light_mode_colour', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dark_mode_colour', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cyclephaseinfos_created_at'), 'cyclephaseinfos', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_table('periodhistories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_prediction', sa.Boolean(), nullable=False),
    sa.Column('is_ongoing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodhistories_created_at'), 'periodhistories', ['created_at'], unique=False)
    op.create_index(op.f('ix_periodhistories_user_id'), 'periodhistories', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_weight', sa.Integer(), nullable=True),
    sa.Column('current_height', sa.Integer(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('ongoing_mens', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_created_at'), 'profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('cycles',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('cycle_start_date', sa.Date(), nullable=False),
    sa.Column('cycle_end_date', sa.Date(), nullable=True),
    sa.Column('cycle_length', sa.Integer(), nullable=True),
    sa.Column('menstrual_start', sa.Date(), nullable=True),
    sa.Column('menstrual_end', sa.Date(), nullable=True),
    sa.Column('follicular_start', sa.Date(), nullable=True),
    sa.Column('follicular_end', sa.Date(), nullable=True),
    sa.Column('ovulation_start', sa.Date(), nullable=True),
    sa.Column('ovulation_end', sa.Date(), nullable=True),
    sa.Column('luteal_start', sa.Date(), nullable=True),
    sa.Column('luteal_end', sa.Date(), nullable=True),
    sa.Column('is_prediction', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['periodhistories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycles_created_at'), 'cycles', ['created_at'], unique=False)
    op.create_index(op.f('ix_cycles_user_id'), 'cycles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cycles_user_id'), table_name='cycles')
    op.drop_index(op.f('ix_cycles_created_at'), table_name='cycles')
    op.drop_table('cycles')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_created_at'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_periodhistories_user_id'), table_name='periodhistories')
    op.drop_index(op.f('ix_periodhistories_created_at'), table_name='periodhistories')
    op.drop_table('periodhistories')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cyclephaseinfos_created_at'), table_name='cyclephaseinfos')
    op.drop_table('cyclephaseinfos')
    # ### end Alembic commands ###
