"""add cycle duration column in profiles

Revision ID: 5894ecc4c15e
Revises: 979ceef2466c
Create Date: 2025-05-01 01:58:22.357392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5894ecc4c15e'
down_revision: Union[str, None] = '979ceef2466c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('average_cycle_duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'average_cycle_duration')
    # ### end Alembic commands ###
