"""add mens column to profile table

Revision ID: 979ceef2466c
Revises: 4d52bfddcc68
Create Date: 2025-05-01 01:21:57.066789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979ceef2466c'
down_revision: Union[str, None] = '4d52bfddcc68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avg_mens_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'avg_mens_duration')
    # ### end Alembic commands ###
